name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Flutter CLI
      uses: steebchen/flutter@v1.0.0
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
    - name: Clean dependencies
      run: flutter clean
    - name: Upgrade dependencies
      run: flutter upgrade
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: pub run test
